blueprint:
  name: Camera Snapshot on Detection with Notification

description: |
This automation takes a camera snapshot when a specific sensor (like motion or person detection) is triggered.
The snapshot is saved in a dedicated folder inside the `/config/www/snapshots/` directory and can optionally send a notification with the image attached.

platform: automation

input:
motion_entity:
name: Motion or Person Sensor
description: Select the binary sensor that will trigger this automation (e.g., a motion sensor, person sensor, etc.).
selector:
entity:
domain: binary_sensor
device_class:
- motion
- occupancy
- presence

camera_entity:
name: Camera
description: Select the camera you want to take a snapshot from.
selector:
entity:
domain: camera

send_notification:
name: Send Notification
description: If enabled, a notification will be sent when motion is detected.
default: true

notify_device:
name: Notification Device or Group
description: The device or service to send the notification to (only used if "Send Notification" is enabled).
selector:
service:
domain: notify

notification_title:
name: (Optional) Notification Title
description: The title for the notification message. (Defaults to blank)
default: ""

notification_message:
name: Notification Message
description: The main content of the notification message.
default: "Motion detected by {{ state_attr(motion_entity, 'friendly_name') }}."

variables:
camera_name: "{{ state_attr(camera_entity, 'friendly_name') | slugify }}"
snapshot_filename: "snapshot_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
snapshot_folder_path: "/config/www/snapshots/{{ camera_name }}"
snapshot_full_filepath: "{{ snapshot_folder_path }}/{{ snapshot_filename }}"
snapshot_public_url: "/local/snapshots/{{ camera_name }}/{{ snapshot_filename }}"
send_notification_bool: !input send_notification

trigger:
- platform: state
entity_id: !input motion_entity
from: "off"
to: "on"

action:
- service: shell_command.create_directory
data:
directory: "{{ snapshot_folder_path }}"

- service: camera.snapshot
target:
entity_id: !input camera_entity
data:
filename: "{{ snapshot_full_filepath }}"

- delay:
seconds: 1

- if: {{ send_notification_bool }}
- service: !input notify_device
data:
title: !input notification_title
message: !input notification_message
clickAction: "/lovelace/default_view?entityId={{ camera_entity }}"
image: "{{ snapshot_public_url }}"

mode: single
