blueprint:
  name: Custom Person Detection with Conditional Snapshot Notification
  description: Triggers a notification with a camera snapshot when a person is detected,
    conditionally based on a toggle, with dynamic snapshot naming.
  domain: automation
  input:
    person_detection_sensor:
      name: Person Detection Sensor
      description: Select the binary sensor that turns ON when a person is detected.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
          multiple: false
    camera_entity_for_snapshot:
      name: Camera for Snapshot
      description: Select the camera entity to take the snapshot from.
      selector:
        entity:
          domain: camera
          multiple: false
    notification_toggle:
      name: Notification Toggle (Input Boolean)
      description: Select an input_boolean entity to control whether notifications are sent.
      selector:
        entity:
          domain: input_boolean
          multiple: false
    notify_target:
      name: Notification Target
      description: Select one or more individual mobile app devices (e.g., mobile_app.my_phone)
        or notification groups (e.g., notify.all_devices) to send the alert to.
      selector:
        target:
          entity:
            domain:
              - mobile_app
              - notify
    snapshot_base_path:
      name: Snapshot Base Path
      description: Base directory for snapshots (e.g., /config/www/snapshots/).
        Ensure this path is accessible by Home Assistant.
      default: /config/www/snapshots
      selector:
        text:
    notification_title:
      name: Notification Title
      description: Title for the notification.
      default: Person Detected!
      selector:
        text:
    notification_message:
      name: Notification Message
      description: Message content for the notification.
      default: Person Detected
      selector:
        text:

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input person_detection_sensor
    to: 'on'

action:
  - variables:
      # Construct the dynamic filename: base_path/YYYY-MM-DD/camera_name_HHMMSS.jpg
      # Uses the current date for the folder, and the camera's friendly name (slugified)
      # and current time for the filename.
      generated_snapshot_filename: >
        {{ [
          (snapshot_base_path | default('/config/www/snapshots')),
          now().strftime('%Y-%m-%d'),
          (state_attr(camera_entity_for_snapshot, 'friendly_name') | slugify),
          (now().strftime('%H%M%S') + '.jpg')
        ] | join('/') }}
  - service: camera.snapshot
    data:
      entity_id: !input camera_entity_for_snapshot
      filename: "{{ generated_snapshot_filename }}"
  - delay:
      milliseconds: 500 # Give the snapshot a moment to save
  - if:
      - condition: state
        entity_id: !input notification_toggle
        state: "on"
    then:
      - service: notify.notify
        target: !input notify_target
        data:
          title: !input notification_title
          message: "{{ notification_message }} from {{ states(camera_entity_for_snapshot) }}"
          data:
            image: "{{ generated_snapshot_filename }}"
