blueprint:
  name: Camera Notification on Person Detection
  description: >
    Triggers when a selected binary sensor turns on, takes a snapshot from the selected camera,
    and sends a notification if a toggle (e.g., input_boolean) is enabled.
  domain: automation
  input:
    motion_sensor:
      name: Motion or Person Sensor
      selector:
        entity:
          domain: binary_sensor
    camera_entity:
      name: Camera
      selector:
        entity:
          domain: camera
    snapshot_filename:
      name: Snapshot File Path
      description: Full path where the snapshot should be saved (e.g., /media/snapshot/basement/snapshot.jpg)
      default: /media/snapshot/basement/snapshot.jpg
    notification_toggle:
      name: Notification Toggle
      description: Input boolean to enable or disable notifications
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"

condition: []

action:
  - service: camera.snapshot
    target:
      entity_id: !input camera_entity
    data:
      filename: !input snapshot_filename

  - if:
      - condition: state
        entity_id: !input notification_toggle
        state: "on"
    then:
      - service: notify.all_devices
        data:
          message: Person Detected
          data:
            image: !input snapshot_filename

mode: single
