blueprint:
  name: Camera Notification on Person Detection (Dynamic Path)
  description: >
    When a binary sensor turns on (e.g., motion or person detected), this takes a snapshot
    from the selected camera and sends a notification if the notification toggle is enabled.
    The snapshot filename is dynamically based on the camera entity ID.
  domain: automation
  input:
    motion_sensor:
      name: Motion or Person Sensor
      selector:
        entity:
          domain: binary_sensor
    camera_entity:
      name: Camera
      selector:
        entity:
          domain: camera
    notification_toggle:
      name: Notification Toggle
      description: Input boolean to enable/disable camera snapshot notifications.
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"

condition: []

action:
  - variables:
      camera_id: !input camera_entity
      snapshot_path: >
        {{ "/media/snapshot/" + camera_id.split(".")[1] + "/snapshot_" + camera_id.split(".")[1] + ".jpg" }}

  - service: camera.snapshot
    target:
      entity_id: !input camera_entity
    data:
      filename: "{{ snapshot_path }}"

  - if:
      - condition: state
        entity_id: !input notification_toggle
        state: "on"
    then:
      - service: notify.all_devices
        data:
          message: Person Detected at {{ camera_id }}
          data:
            image: "{{ snapshot_path }}"

mode: single
