blueprint:
  name: Person Detected - Snapshot and Notify (Fixed Group)
  description: >
    Takes a snapshot from a camera and sends a notification when a person is
    detected by a binary sensor. Notifications can be toggled on/off with an
    input boolean and are always sent to the `notify.all_devices` group.
  domain: automation
  source_url: https://github.com/your-github-profile/your-repo/basement_person_detector.yaml

  input:
    motion_sensor:
      name: Person Detection Sensor
      description: The binary sensor that reports when a person is detected.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    camera_entity:
      name: Camera Entity
      description: The camera entity to take a snapshot from.
      selector:
        entity:
          domain: camera
    notification_toggle:
      name: Notification Toggle Helper
      description: An optional input boolean helper to enable or disable notifications.
      selector:
        entity:
          domain: input_boolean
      default: null

mode: single

variables:
  snapshot_filename: "/config/www/snapshots/snapshot_{{ now().strftime('%Y%m%d_%H%M%S') }}_{{ states(camera_entity).name | lower | replace(' ', '_') }}.jpg"

trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"

condition: []

action:
  - service: camera.snapshot
    data:
      filename: "{{ snapshot_filename }}"
    target:
      entity_id: !input camera_entity

  - if:
      - condition: template
        value_template: >
          {% if notification_toggle is not none %}
            {{ states(notification_toggle) == 'on' }}
          {% else %}
            true
          {% endif %}
    then:
      - service: notify.all_devices
        data:
          title: "Person Detected"
          message: "A person was detected by {{ states(motion_sensor).name }}."
          data:
            image: "{{ snapshot_filename | replace('/config/www', '/local') }}"
