blueprint:
  name: Person Detected - Camera Notification
  description: >
    Sends a snapshot notification when motion is detected. 
    Includes a timestamped image and link to the live feed.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
    camera:
      name: Camera
      selector:
        entity:
          domain: camera
    camera_name:
      name: Camera Name
      selector:
        text:

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"

variables:
  camera_entity: !input camera
  label: !input camera_name
  safe_label: "{{ label | lower | replace(' ', '_') | regex_replace('[^a-z0-9_]', '') }}"
  timestamp: "{{ now().strftime('%Y%m%d_%H%M%S') }}"
  snapshot_filename: "/media/snapshots/{{ safe_label }}/snapshot_{{ safe_label }}_{{ timestamp }}.jpg"
  snapshot_url: "/media/snapshots/{{ safe_label }}/snapshot_{{ safe_label }}_{{ timestamp }}.jpg"

condition: []

action:
  # Ensure the snapshot directory exists
  - service: shell_command.create_snapshot_dir
    data:
      dir: "/media/snapshots/{{ safe_label }}"

  # Take the snapshot
  - service: camera.snapshot
    data:
      filename: "{{ snapshot_filename }}"
    target:
      entity_id: "{{ camera_entity }}"

  # Wait a few seconds for the snapshot to be saved
  - delay: "00:00:10"

  # Only notify if the camera_notifications toggle is on
  - if:
      - condition: state
        entity_id: input_boolean.camera_notifications
        state: "on"
    then:
      - service: notify.all_devices
        data:
          message: "Person Detected - {{ label | title }}"
          data:
            image: "{{ snapshot_url }}"
            actions:
              - action: "URI"
                title: "View Live"
                uri: "homeassistant://entity/{{ camera_entity }}"

mode: single
